[workspace]
members = [
    "distribution", 
    "libbridge",
    "libcgroups", 
    "libcni",
    "libcontainer", 
    "libflannel",
    "libfuse-fs", 
    "libipam", 
    "rkb",
    "rkl",
]

default-members = ["distribution", "rkl", "libbridge", "libipam"]
resolver = "1"

[workspace.dependencies]
distribution = { path = "distribution" }
libcgroups = { path = "libcgroups" }
libcni = { path = "libcni" }
libcontainer = { path = "libcontainer" }
