[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
uuid = { version = "1.15.1", features = ["v4"] }
clap = { version = "4.5.32", features = ["derive"] }
fuse3 = { version = "0.8.1", features = ["tokio-runtime", "unprivileged"] }
tokio = { version = "1.44.0", features = ["full"] }
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
radix_trie = "0.2.1"
futures = "0.3.31"
libc = "0.2.171"
serde_json = "1.0.128"
vm-memory = "0.16.1"
fuse-backend-rs = "0.12.1"
bytes = "1.10.1"
futures-util = "0.3.31"
log = "0.4.26"
env_logger = "0.11.7"
vmm-sys-util = "0.12.1"
openssl = { version = "0.10.71", features = ["vendored"] }

# Local patches - typically git references
[patch.crates-io]
