[package]
name = "logging_macros"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["proc-macro"]

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }